/**
 * AR.IO Gateway
 * Copyright (C) 2022 - 2026 Permanent Data Solutions, Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//! AR.IO token supply: fetch + decode + sanity-check.
//!
//! The AR.IO network migrated from AO to Solana. This module reads live
//! supply straight from Solana (native fetch JSON-RPC, no SDK dependency)
//! by reading four FIXED, immutable accounts:
//!
//!   - ARIO SPL mint        -> total supply (live, tracks burns)
//!   - ArioConfig PDA       -> circulating(liquid) / locked supply
//!   - GatewaySettings PDA  -> staked / delegated / withdrawn counters
//!   - protocol token acct  -> live reward-reserve balance (protocolBalance)
//!
//! Account addresses, byte offsets, and the pre-cutoff vault snapshot are
//! regenerated by scripts/gen-supply-snapshot.mts in the ar-io-sdk repo.
//!
//! TOTAL — read from the mint, NOT from ArioConfig:
//!   `ArioConfig.total_supply` is a genesis DECLARATION, written once by
//!   `finalize_supply` and never updated. ARIO is a standard SPL token, so any
//!   holder can burn their own tokens — two holders have already done so via a
//!   wallet-cleanup incinerator, putting real supply 373.297318 ARIO below the
//!   1B declaration. The mint's own `supply` field tracks every burn (and any
//!   future mint) in real time, so it is the only correct source for a number
//!   that price aggregators consume. Note `finalize_migration` permanently
//!   disables `finalize_supply`, after which the declaration can NEVER be
//!   corrected — one more reason not to depend on it.
//!
//! CIRCULATING — historical metric preserved across the migration:
//!   Migration RESET every Solana vault's startTimestamp, destroying the
//!   on-chain Dec-8-2025 cutoff signal. But the pre-cutoff vaults are
//!   balance-immutable, so their locked amounts + unlock dates are
//!   snapshotted from AO below (PRE_CUTOFF_LOCK_BUCKETS). At runtime we sum
//!   the buckets that haven't unlocked yet and report
//!   circulating = total - lockedBeforeCutoff, exactly as the AO handler
//!   did. `liquid` remains the strict on-chain circulating balance.

export const MARIO_PER_ARIO = 1_000_000;

// ===========================================================================
// GENERATED SNAPSHOT — regenerate with ar-io-sdk scripts/gen-supply-snapshot.mts
// ===========================================================================
export const ARIO_MINT = "DcNnMuFxwhgV4WY1HVSaSEgr92bv2b1vUvEKiNxWqHdF";
export const ARIO_CONFIG_PDA = "EdtCcYk9RAHyakTSBwtJit6SJcrrk9hj82sASekszLf5";
export const GAR_SETTINGS_PDA = "7wphJhrg5rpoWNjRqKfyeMPV24e6qrJwfjGKwQasAf54";
export const PROTOCOL_TOKEN_ACCOUNT = "6Sj3DQAynK916KfBHUZxnG4aDKdqFpBVPCNdD4X6Vrj5";

export interface LockBucket {
  endTimestamp: number;
  balance: number;
}

// Locked balances (mARIO) from vaults created before the Dec 8 2025 cutoff,
// aggregated by unlock date (unix ms). Sum entries with endTimestamp > now.
export const PRE_CUTOFF_LOCK_BUCKETS: LockBucket[] = [
  { endTimestamp: 1781913600000, balance: 17636188406250 },
  { endTimestamp: 1781914453915, balance: 111111111111 },
  { endTimestamp: 1781915214188, balance: 1379842000000 },
  { endTimestamp: 1781915284783, balance: 138888888888 },
  { endTimestamp: 1781916038752, balance: 27777000000 },
  { endTimestamp: 1781919922748, balance: 177408000000 },
  { endTimestamp: 1781920178237, balance: 394240000000 },
  { endTimestamp: 1784505600000, balance: 17636188406250 },
  { endTimestamp: 1784506465493, balance: 111111111111 },
  { endTimestamp: 1784507264839, balance: 1379842000000 },
  { endTimestamp: 1784507301564, balance: 138888888888 },
  { endTimestamp: 1784508051817, balance: 27777000000 },
  { endTimestamp: 1784511941594, balance: 177408000000 },
  { endTimestamp: 1784512185852, balance: 394240000000 },
  { endTimestamp: 1787184000000, balance: 17636188406250 },
  { endTimestamp: 1787184877648, balance: 111111111111 },
  { endTimestamp: 1787185677999, balance: 1379842000000 },
  { endTimestamp: 1787185717622, balance: 138888888888 },
  { endTimestamp: 1787186540823, balance: 27777000000 },
  { endTimestamp: 1787190349681, balance: 177408000000 },
  { endTimestamp: 1787190594538, balance: 394240000000 },
  { endTimestamp: 1789862400000, balance: 8765643406250 },
  { endTimestamp: 1789863286708, balance: 111111111111 },
  { endTimestamp: 1789864128714, balance: 138888888888 },
  { endTimestamp: 1789864955849, balance: 27777000000 },
  { endTimestamp: 1792454400000, balance: 8765643406250 },
  { endTimestamp: 1792455295906, balance: 111111111111 },
  { endTimestamp: 1792456148557, balance: 138888888888 },
  { endTimestamp: 1792456965115, balance: 27777000000 },
  { endTimestamp: 1795132800000, balance: 8765643406250 },
  { endTimestamp: 1795133704693, balance: 111111111111 },
  { endTimestamp: 1795134557021, balance: 138888888888 },
  { endTimestamp: 1795135377612, balance: 27777000000 },
  { endTimestamp: 1797724800000, balance: 8765643406250 },
  { endTimestamp: 1797725712853, balance: 111111111111 },
  { endTimestamp: 1797726564773, balance: 138888888888 },
  { endTimestamp: 1797727387985, balance: 27777000000 },
  { endTimestamp: 1800403200000, balance: 8765643406250 },
  { endTimestamp: 1800404121294, balance: 111111111111 },
  { endTimestamp: 1800404973841, balance: 138888888888 },
  { endTimestamp: 1800405816841, balance: 27777000000 },
  { endTimestamp: 1803081600000, balance: 8765643406250 },
  { endTimestamp: 1803082550157, balance: 111111111111 },
  { endTimestamp: 1803083381571, balance: 138888888888 },
  { endTimestamp: 1803084228875, balance: 27777000000 },
  { endTimestamp: 1805500800000, balance: 8661477406250 },
  { endTimestamp: 1805501758861, balance: 111111111111 },
  { endTimestamp: 1805502589550, balance: 138888888888 },
  { endTimestamp: 1805503440832, balance: 27777000000 },
  { endTimestamp: 1808179200000, balance: 8661477406250 },
  { endTimestamp: 1808180169096, balance: 111111111111 },
  { endTimestamp: 1808181007415, balance: 138888888888 },
  { endTimestamp: 1808181848172, balance: 27777000000 },
  { endTimestamp: 1810771200000, balance: 8661477406250 },
  { endTimestamp: 1810772178899, balance: 111111111111 },
  { endTimestamp: 1810773026163, balance: 138888888888 },
  { endTimestamp: 1810773855349, balance: 27777000000 },
  { endTimestamp: 1813449600000, balance: 8661477406250 },
  { endTimestamp: 1813450595102, balance: 111111111111 },
  { endTimestamp: 1813451435841, balance: 138888888888 },
  { endTimestamp: 1813452263377, balance: 27777000000 },
  { endTimestamp: 1816041600000, balance: 8661477406250 },
  { endTimestamp: 1816042606633, balance: 111111111111 },
  { endTimestamp: 1816043445716, balance: 138888888888 },
  { endTimestamp: 1816044273716, balance: 27777000000 },
  { endTimestamp: 1818720000000, balance: 8661477406250 },
  { endTimestamp: 1818721016304, balance: 111111111111 },
  { endTimestamp: 1818721853553, balance: 138888888888 },
  { endTimestamp: 1818722682541, balance: 27777000000 },
  { endTimestamp: 1821398400000, balance: 8661477406250 },
  { endTimestamp: 1821399424757, balance: 111111111111 },
  { endTimestamp: 1821400261462, balance: 138888888888 },
  { endTimestamp: 1821401095707, balance: 27777000000 },
  { endTimestamp: 1823990400000, balance: 8661477406250 },
  { endTimestamp: 1823991432550, balance: 111111111111 },
  { endTimestamp: 1823992269638, balance: 138888888888 },
  { endTimestamp: 1823993131252, balance: 27777000000 },
  { endTimestamp: 1826668800000, balance: 8661477406250 },
  { endTimestamp: 1826669840600, balance: 111111111111 },
  { endTimestamp: 1826670677578, balance: 138888888888 },
  { endTimestamp: 1826671544386, balance: 27777000000 },
  { endTimestamp: 1829260800000, balance: 8661477406250 },
  { endTimestamp: 1829261849495, balance: 111111111111 },
  { endTimestamp: 1829262686343, balance: 138888888888 },
  { endTimestamp: 1829263558320, balance: 27777000000 },
  { endTimestamp: 1831939200000, balance: 8661477406250 },
  { endTimestamp: 1831940262503, balance: 111111111111 },
  { endTimestamp: 1831941095308, balance: 138888888888 },
  { endTimestamp: 1831941967911, balance: 27777000000 },
  { endTimestamp: 1834617600000, balance: 8661477406250 },
  { endTimestamp: 1834618672639, balance: 111111111111 },
  { endTimestamp: 1834619502782, balance: 138888888888 },
  { endTimestamp: 1834620379378, balance: 27777000000 },
  { endTimestamp: 1837123200000, balance: 4003157406250 },
  { endTimestamp: 1839801600000, balance: 4003157406250 },
  { endTimestamp: 1842393600000, balance: 4003157406250 },
  { endTimestamp: 1845072000000, balance: 4003157406250 },
  { endTimestamp: 1847664000000, balance: 4003157406250 },
  { endTimestamp: 1850342400000, balance: 4003157406250 },
  { endTimestamp: 1853020800000, balance: 4003157406250 },
  { endTimestamp: 1855612800000, balance: 4003157406250 },
  { endTimestamp: 1858291200000, balance: 4003157406250 },
  { endTimestamp: 1860883200000, balance: 4003157406250 },
  { endTimestamp: 1863561600000, balance: 4003157406250 },
  { endTimestamp: 1866240000000, balance: 4003157406250 },
  { endTimestamp: 1868659200000, balance: 4003157406250 },
  { endTimestamp: 1871337600000, balance: 4003157406250 },
  { endTimestamp: 1873929600000, balance: 4003157406250 },
  { endTimestamp: 1876608000000, balance: 4003157406250 },
  { endTimestamp: 1879200000000, balance: 4003157406250 },
  { endTimestamp: 1881878400000, balance: 4003157406250 },
  { endTimestamp: 1884556800000, balance: 4003157406250 },
  { endTimestamp: 1887148800000, balance: 4003157406250 },
  { endTimestamp: 1889827200000, balance: 4003157406250 },
  { endTimestamp: 1892419200000, balance: 4003157406250 },
  { endTimestamp: 1895097600000, balance: 4003157406250 },
  { endTimestamp: 1897776000000, balance: 4003157406250 },
  { endTimestamp: 1900195200000, balance: 4003157406250 },
  { endTimestamp: 1902873600000, balance: 4003157406250 },
  { endTimestamp: 1905465600000, balance: 4003157406250 },
  { endTimestamp: 1908144000000, balance: 4003157406250 },
  { endTimestamp: 1910736000000, balance: 4003157406250 },
  { endTimestamp: 1913414400000, balance: 4003157406250 },
  { endTimestamp: 1916092800000, balance: 4003157406250 },
  { endTimestamp: 1918684800000, balance: 4003157406250 },
  { endTimestamp: 1921363200000, balance: 4003157406250 },
  { endTimestamp: 1923955200000, balance: 4003157406250 },
  { endTimestamp: 1926633600000, balance: 4003157406250 },
  { endTimestamp: 1929312000000, balance: 4003157406250 },
];

// Account byte offsets (Codama struct layouts from @ar.io/solana-contracts).
// SPL Mint: [4 mintAuthorityOption][32 mintAuthority][u64 supply]...
const OFF_MINT_SUPPLY = 36;
// ArioConfig: [8 disc][32 authority][32 mint][32 arns][32 treasury][u64 total]...
// (`total` @136 is the frozen genesis declaration — see the TOTAL note above;
// we read supply from the mint instead.)
const OFF_CONFIG_CIRCULATING = 152;
const OFF_CONFIG_LOCKED = 160;
// GatewaySettings: protocolTokenAccount@189; counters after arnsProgramId@221.
const OFF_GAR_TOTAL_STAKED = 253;
const OFF_GAR_TOTAL_DELEGATED = 261;
const OFF_GAR_TOTAL_WITHDRAWN = 269;
// SPL token account: [32 mint][32 owner][u64 amount]
const OFF_TOKEN_AMOUNT = 64;

export interface DecodedSupply {
  total: number;
  circulating: number;
  locked: number;
  staked: number;
  delegated: number;
  withdrawn: number;
  protocolBalance: number;
}

/** Final response shape, denominated in ARIO (not mARIO). */
export interface SupplyResponse {
  total: number;
  circulating: number;
  locked: number;
  staked: number;
  delegated: number;
  withdrawn: number;
  protocolBalance: number;
  liquid: number;
}

/**
 * Portable little-endian u64 read. ARIO supply caps at 1B * 1e6 ≈ 2^50, well
 * under Number.MAX_SAFE_INTEGER, so a Number is exact.
 */
export function readU64LE(buf: Buffer, offset: number): number {
  let value = 0n;
  for (let i = 7; i >= 0; i--) {
    value = (value << 8n) | BigInt(buf[offset + i]);
  }
  return Number(value);
}

interface RawAccounts {
  mint: Buffer;
  config: Buffer;
  gar: Buffer;
  token: Buffer;
}

/**
 * Atomically fetch the four fixed accounts (same slot) via a single
 * getMultipleAccounts JSON-RPC call, returning decoded Buffers.
 */
export async function fetchSupplyAccounts(
  rpcUrl: string,
  signal: AbortSignal,
): Promise<RawAccounts> {
  const response = await fetch(rpcUrl, {
    method: "POST",
    signal,
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      jsonrpc: "2.0",
      id: 1,
      method: "getMultipleAccounts",
      params: [
        [ARIO_MINT, ARIO_CONFIG_PDA, GAR_SETTINGS_PDA, PROTOCOL_TOKEN_ACCOUNT],
        { encoding: "base64", commitment: "confirmed" },
      ],
    }),
  });

  if (!response.ok) {
    throw new Error(`Solana RPC error: ${response.statusText}`);
  }

  const json = (await response.json()) as {
    error?: unknown;
    result?: { value?: Array<{ data: [string, string] } | null> };
  };
  if (json.error) {
    throw new Error(`Solana RPC error: ${JSON.stringify(json.error)}`);
  }

  const values = json.result?.value;
  if (!Array.isArray(values) || values.length !== 4) {
    throw new Error("Unexpected getMultipleAccounts response shape");
  }

  const addresses = [
    ARIO_MINT,
    ARIO_CONFIG_PDA,
    GAR_SETTINGS_PDA,
    PROTOCOL_TOKEN_ACCOUNT,
  ];
  const [mint, config, gar, token] = values.map((v, i) => {
    if (!v) {
      throw new Error(`Account ${addresses[i]} not found`);
    }
    return Buffer.from(v.data[0], "base64");
  });

  return { mint, config, gar, token };
}

/**
 * Decode the on-chain supply buckets (mARIO) from the four accounts.
 *
 * `total` is the mint's live `supply`, so it reflects holder burns — NOT the
 * frozen ArioConfig.total_supply declaration (see the TOTAL note at the top).
 * `protocolBalance` is the live reward-reserve token-account balance — NOT
 * the folded ArioConfig.protocol_balance accounting field, which
 * double-counts the staking buckets.
 */
export function decodeSupply({
  mint,
  config,
  gar,
  token,
}: RawAccounts): DecodedSupply {
  // Defensive: a program upgrade that changes account layout would shift
  // these offsets; require the accounts to be at least as large as the
  // fields we read.
  if (mint.length < OFF_MINT_SUPPLY + 8) {
    throw new Error(`ARIO mint too small (${mint.length}B)`);
  }
  if (config.length < OFF_CONFIG_LOCKED + 8) {
    throw new Error(`ArioConfig too small (${config.length}B)`);
  }
  if (gar.length < OFF_GAR_TOTAL_WITHDRAWN + 8) {
    throw new Error(`GatewaySettings too small (${gar.length}B)`);
  }
  if (token.length < OFF_TOKEN_AMOUNT + 8) {
    throw new Error(`Protocol token account too small (${token.length}B)`);
  }

  return {
    total: readU64LE(mint, OFF_MINT_SUPPLY),
    circulating: readU64LE(config, OFF_CONFIG_CIRCULATING),
    locked: readU64LE(config, OFF_CONFIG_LOCKED),
    staked: readU64LE(gar, OFF_GAR_TOTAL_STAKED),
    delegated: readU64LE(gar, OFF_GAR_TOTAL_DELEGATED),
    withdrawn: readU64LE(gar, OFF_GAR_TOTAL_WITHDRAWN),
    protocolBalance: readU64LE(token, OFF_TOKEN_AMOUNT),
  };
}

/**
 * Plausibility checks to catch a layout drift (program upgrade, or an SPL Mint
 * layout change under `total`) before we serve garbage to price aggregators.
 * Deliberately loose — a real layout error yields wildly out-of-range or
 * negative numbers, not a fraction-of-a-percent gap, so ordinary holder burns
 * pass through untouched while a misread offset trips the range check.
 */
export function assertPlausible(supply: DecodedSupply): void {
  const { total } = supply;
  if (
    !(
      total > 900_000_000 * MARIO_PER_ARIO &&
      total < 1_100_000_000 * MARIO_PER_ARIO
    )
  ) {
    throw new Error(`Implausible total supply: ${total} mARIO`);
  }
  for (const key of [
    "circulating",
    "locked",
    "staked",
    "delegated",
    "withdrawn",
    "protocolBalance",
  ] as const) {
    const v = supply[key];
    if (!(v >= 0 && v <= total)) {
      throw new Error(`Implausible ${key}: ${v} mARIO`);
    }
  }
}

/** Sum of pre-cutoff vault buckets that have not unlocked yet, as of `now`. */
export function lockedBeforeCutoff(now: number, buckets: LockBucket[] = PRE_CUTOFF_LOCK_BUCKETS): number {
  return buckets.reduce(
    (sum, bucket) => (bucket.endTimestamp > now ? sum + bucket.balance : sum),
    0,
  );
}

/**
 * Fetch, decode, sanity-check, and shape the full supply response
 * (denominated in ARIO). Throws on any failure — caller decides whether to
 * fall back to a cached value.
 */
export async function getSupply(rpcUrl: string, signal: AbortSignal): Promise<SupplyResponse> {
  const accounts = await fetchSupplyAccounts(rpcUrl, signal);
  const supplyData = decodeSupply(accounts);
  assertPlausible(supplyData);

  const now = Date.now();
  const locked = lockedBeforeCutoff(now);

  const mario = {
    ...supplyData,
    // Circulating excludes only the pre-cutoff vesting vaults still locked.
    circulating: supplyData.total - locked,
    // Liquid is the strict on-chain circulating (freely transferable) balance.
    liquid: supplyData.circulating,
  };

  // convert the values to be denominated in ARIO (from mARIO)
  return Object.fromEntries(
    Object.entries(mario).map(([key, value]) => [key, value / MARIO_PER_ARIO]),
  ) as unknown as SupplyResponse;
}
